### ISSUE TITLE
Failed to inject axe-core into frame

### ISSUE THREAD

**Issue by spencerpowell** [dequelabs/axe-puppeteer#25]
console.error node_modules/axe-puppeteer/dist/axePuppeteer.js:32
    Failed to inject axe-core into frame (https://js.stripe.com/v3/controller-2ace0711417171a8a30d52b4cb011e58.html)

Is there a way to prevent axe-puppeteer from injecting axe-core into certain frames?

This is the code I have currently:
`const { violations } = await new AxePuppeteer(populatedPage).analyze();`

**Comment by stephenmathieson** [comment]
Not at the moment, no. There is no way to tell it to not attempt to inject `axe-core` into each frame.

This could be an interesting feature to add tho. We could add an option (something like `ignoredIframeSelectors = ['iframe[name="your_funky_frame"]']`) and add a [`.filter()` to remove any matching iframes in this loop](https://github.com/dequelabs/axe-puppeteer/blob/develop/src/axePuppeteer.ts#L56-L59).

Would be more than happy to review/merge a PR adding this! 😄

**Comment by spencerpowell** [comment]
@stephenmathieson Thanks, yeah that would be a cool feature.  I can look into adding it when I get some time.

**Comment by okeul** [comment]
It would be great !

Same here:
```
Failed to inject axe-core into frame (https://pixel.mathtag.com/sync/iframe?mt_uuid=xxx)
Failed to inject axe-core into frame (https://tr.snapchat.com/p)
Failed to inject axe-core into frame (https://t.svtrd.com/collect/iframe/xxx)
...
```

**Comment by HariMannem** [comment]
@okeul: Same issue I am facing. Did you find any solution to dissolve the error: **Failed to inject axe-core into frame**?

**Comment by michael-siek** [comment]
Hey @HariMannem do you mind sharing a code snippet?

**Comment by HariMannem** [comment]
@michael-siek : please check the below image. In my function I just using analyze() and pushing the results into totalViolations. whenever I call the accessibilityCheck(), In console it's keep on showing the error -  **..Failed to inject axe-core into one of the iframes!**


![image](https://user-images.githubusercontent.com/32463531/70645304-bf23b980-1c12-11ea-8f6a-508ea378b039.png)

**Comment by michael-siek** [comment]
Moved to axe-core-npm repo: https://github.com/dequelabs/axe-core-npm/issues/98
