### ISSUE TITLE
Using `withTags` vs `options` with rule id do not yield the same results

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-puppeteer#55]
When using `axe-puppeteer` for generating some implementations for [ACT Rules](https://act-rules.github.io/), I noticed that the results are not the same for these calls.

More context:
For the URL `https://act-rules.github.io/testcases/b33eff/9aec958042a6a5f50d8ab1e0ea02a82144db776d.html` 

The below returns an empty array `[]`, where as it is expected to run the rule `css-orientation-lock`. 
```
await new AxePuppeteer(page, axeSource)
      .options({
        runOnly: {
          type: 'tag',
          values: ['wcag134']
        },
        reporter: 'raw'
      })
      .analyze()
```

The same happens when using `.withTags(`wcag134`)`.

But running using `.options()` and with type `rule` and rule id yeilds the correct results.

**Comment by michael-siek** [comment]
We have move this package here. https://github.com/dequelabs/axe-core-npm. Issue has been reopened here https://github.com/dequelabs/axe-core-npm/issues/99
