### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by lfdebrux** [dequelabs/axe-puppeteer#57]
Is it possible for the latest version of this package to be released to NPM?

The current version on NPM (1.0.0) does not include PR #53, which means that when installing `npm` complains about the `puppeteer` peer dependency if you have the latest version of puppeteer installed, which is confusing.

**Comment by stephenmathieson** [comment]
Yes, we'll get one together soon. In the meantime, you can do this:

```
npm install axe-puppeteer@next
```

**Comment by stephenmathieson** [comment]
`v1.1.0` was published to npm! See https://circleci.com/gh/dequelabs/axe-puppeteer/752
