### ISSUE TITLE
exclude() doesn't work with string arrays

### ISSUE THREAD

**Issue by Juuro** [dequelabs/axe-puppeteer#58]
If I understand the [documentation](https://github.com/dequelabs/axe-puppeteer#axepuppeteerexcludeselector-string--string) the exclude function should work with a string array like that:

```
new AxePuppeteer(page).exclude(['label', 'button'])
```

Sadly it doesn't. It only works like that:

```
new AxePuppeteer(page).exclude('label').exclude('button')
```

Am I doing something wrong or is this a bug?
I'm using axe-puppeteer v1.0.0 (installed via `yarn add axe-puppeteer@next` as recommended in #57).

**Comment by stephenmathieson** [comment]
Thanks for the bug report. I'll take a look!
