### ISSUE TITLE
Playwright support

### ISSUE THREAD

**Issue by celeryclub** [dequelabs/axe-puppeteer#70]
Hey there. Thanks for building this tool.

I'm curious if you've considered supporting [Playwright](https://github.com/microsoft/playwright) too. The API is very similar, so it seems like it could be a logical fit.

Also happy to help out with this if it's something you're open to.

Thanks!

**Comment by stephenmathieson** [comment]
Hey! We've talked about this a bit internally but haven't had the time to get around to building it. I'll try and spend some "creative time" on it within the next sprint or two.

**Comment by AutoSponge** [comment]
I just did the example test from the readme in playwright and it worked exactly the same.

```js
const { AxePuppeteer } = require('axe-puppeteer')

await page.goto('https://dequeuniversity.com/demo/mars/')
const results = await new AxePuppeteer(page).analyze()
console.log(results)
```

**Comment by stephenmathieson** [comment]
Thanks Paul! It doesn't look like there's too much work to be done here. We can hopefully get something put together soon 😄

**Comment by michael-siek** [comment]
We have moved this package here https://github.com/dequelabs/axe-core-npm/ and have opened an issue within the repo. https://github.com/dequelabs/axe-core-npm/issues/100
