### ISSUE TITLE
Out of memory crash when scanning using axe-puppeteer

### ISSUE THREAD

**Issue by lamaks** [dequelabs/axe-puppeteer#72]
We are experiencing the issue with automation when scanning the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) web site. The Chromium pause the axe with the warning `Paused before potential out-of-memory crash` This is repro with packages (Node 12.16.3):

`"axe-core": "^3.5.4",
"axe-puppeteer": "^1.1.0",
"puppeteer": "^3.3.0"`

The scan of the same web site works when running axe Chrome extension 4.5.1.

Can you please look into memory utilization when running axe-puppeteer.

Thanks

<img width="1203" alt="Screen Shot 2020-06-03 at 7 43 22 PM" src="https://user-images.githubusercontent.com/40576301/83711649-a3eda180-a5d8-11ea-9ee4-fab24b890925.png">

**Comment by WilcoFiers** [comment]
Thanks for reporting. Yeah we'll take a look at it.

**Comment by scurker** [comment]
@lamaks I haven't been able to replicate this yet. I just ran the following script with various versions of puppeteer and node and could not replicate:

```js
const { AxePuppeteer } = require('axe-puppeteer')
const puppeteer = require('puppeteer')

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.setBypassCSP(true)

  await page.goto('https://developer.microsoft.com/en-us/graph/graph-explorer')

  const results = await new AxePuppeteer(page).analyze()
  console.log(results)

  await page.close()
  await browser.close()
})()
```

Are there any additional details you could provide?

**Comment by pownkel** [comment]
@scurker I'm not getting the error message in the console, but I do get memory issues with the script you provided. If I open task manager while the script is running, I see several background instances of Chromium with one that uses an increasing amount of memory and CPU until it crashes:
<img width="540" alt="task manager" src="https://user-images.githubusercontent.com/55459788/88934926-0b6d4980-d236-11ea-9dbf-41aba28738ec.PNG">

I also see an out-of-memory message in chromium devtools following these steps:
1. In the script above, replace `puppeteer.launch()` with `puppeteer.launch({headless:false})`
2. Start the script
3. Open devtools in the chromium window that opens
4. In the sources tab, click the stop sign/pause button (above threads and call stack) and check "pause on caught exceptions"
5. Wait for chromium to crash

Then I see a "Paused before potential out-of-memory crash" message:
<img width="675" alt="chromium oom" src="https://user-images.githubusercontent.com/55459788/88934889-00b2b480-d236-11ea-9d37-1ed9bdfa0ea4.PNG">

I'm using the same versions of node, axe-core, axe-puppeteer, and puppeteer as @lamaks on Windows 10 version 1909

**Comment by lamaks** [comment]
@scurker did you have a chance to look into this issue?

**Comment by lamaks** [comment]
@axe-core/puppeteer package has fix to this issue
